[package]
name = "eventp"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.9"
libc = "0.2"
mockall = { version = "0.13", optional = true }
nix = { version = "0.30", features = ["event"] }
rustc-hash = "2"

[features]
mock = ["dep:mockall"]
