[package]
name = "eventp"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29", features = ["event"] }
thiserror = "2"
vptr = { version = "0.2.2", optional = true }

[features]
default = ["vptr"]
vptr = ["dep:vptr"]

[dev-dependencies]
oneshot = "0.1.11"
