name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly rustfmt
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly
      - name: Check
        run: make check
